import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service — Lulgo',
  description: 'Lulgo terms of service / 服務條款',
}

export default function TermsPage() {
  return (
    <div className="min-h-dvh bg-white">
      <header className="border-b border-gray-100 px-4 py-4">
        <div className="max-w-2xl mx-auto flex items-center justify-between">
          <Link href="/" className="text-lg font-bold text-gray-900">
            Lul<span className="text-orange">go</span> ✨
          </Link>
          <Link href="/" className="text-sm text-gray-500 hover:text-gray-700">← Back</Link>
        </div>
      </header>

      <main className="max-w-2xl mx-auto px-4 py-10">
        <h1 className="text-2xl font-bold text-gray-900 mb-1">Terms of Service</h1>
        <p className="text-sm text-gray-400 mb-8">Last updated: March 31, 2026 / 最後更新：2026年3月31日</p>

        <div className="space-y-8 text-gray-700 text-sm leading-relaxed">

          {/* Section 1 */}
          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">1. Acceptance of Terms / 接受條款</h2>
            <p className="mb-2">
              By using Lulgo, you agree to these terms. If you do not agree, please do not use the service.
            </p>
            <p className="text-gray-500">
              使用 Lulgo 即表示你同意以下條款。如果你唔同意，請唔好使用本服務。
            </p>
          </section>

          {/* Section 2 */}
          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">2. Service Description / 服務說明</h2>
            <p className="mb-2">
              Lulgo is a free AI-powered travel itinerary generator. It uses artificial intelligence to create trip plans based on your input. The service is provided &quot;as is&quot; and is currently free to use.
            </p>
            <p className="text-gray-500">
              Lulgo 係一個免費嘅 AI 旅行行程生成器。佢利用人工智能根據你嘅輸入建立行程計劃。本服務按「現狀」提供，目前免費使用。
            </p>
          </section>

          {/* Section 3 */}
          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">3. Free Tier / 免費使用限制</h2>
            <ul className="list-disc list-inside space-y-1 mb-2">
              <li>Lulgo is currently free with no guaranteed uptime</li>
              <li>We may introduce usage limits or paid tiers in the future</li>
              <li>Trip data is stored for up to 90 days and may be removed</li>
              <li>Rate limiting applies (5 requests per minute)</li>
            </ul>
            <ul className="list-disc list-inside space-y-1 text-gray-500">
              <li>Lulgo 目前免費使用，唔保證服務持續可用</li>
              <li>我們可能喺將來引入使用限制或付費方案</li>
              <li>行程資料最多儲存 90 日，之後可能會被移除</li>
              <li>設有速率限制（每分鐘 5 個請求）</li>
            </ul>
          </section>

          {/* Section 4 */}
          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">4. User Responsibilities / 用戶責任</h2>
            <ul className="list-disc list-inside space-y-1 mb-2">
              <li>You are responsible for verifying all travel information before booking</li>
              <li>Do not use the service for any unlawful purpose</li>
              <li>Do not attempt to abuse, overload, or reverse-engineer the service</li>
              <li>AI-generated itineraries are suggestions only; always verify details independently</li>
            </ul>
            <ul className="list-disc list-inside space-y-1 text-gray-500">
              <li>你有責任喺預訂前核實所有旅行資訊</li>
              <li>唔好將本服務用於任何非法用途</li>
              <li>唔好嘗試濫用、過度使用或逆向工程本服務</li>
              <li>AI 生成嘅行程僅供參考，請自行核實詳情</li>
            </ul>
          </section>

          {/* Section 5 */}
          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">5. AI-Generated Content / AI 生成內容</h2>
            <p className="mb-2">
              Trip itineraries are generated by AI and may contain inaccuracies. Restaurant ratings, opening hours, addresses, and other details may be outdated or incorrect. We validate places against Google Places API, but cannot guarantee 100% accuracy.
            </p>
            <p className="text-gray-500">
              行程由 AI 生成，可能包含不準確嘅資訊。餐廳評分、營業時間、地址等詳情可能過時或有誤。我們會透過 Google Places API 驗證地點，但無法保證 100% 準確。
            </p>
          </section>

          {/* Section 6 */}
          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">6. Disclaimer of Warranty / 免責聲明</h2>
            <p className="mb-2">
              Lulgo is provided <strong>&quot;as is&quot;</strong> without any warranty, express or implied. We make no guarantees regarding the accuracy, reliability, or availability of the service. We are not responsible for any losses or damages arising from the use of AI-generated travel plans.
            </p>
            <p className="text-gray-500">
              Lulgo 按<strong>「現狀」</strong>提供，唔附帶任何明示或暗示嘅保證。我們唔保證服務嘅準確性、可靠性或可用性。我們唔會對因使用 AI 生成嘅旅行計劃而產生嘅任何損失或損害負責。
            </p>
          </section>

          {/* Section 7 */}
          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">7. Changes to Terms / 條款變更</h2>
            <p className="mb-2">
              We may update these terms from time to time. Continued use of Lulgo after changes constitutes acceptance of the new terms.
            </p>
            <p className="text-gray-500">
              我們可能會不時更新呢啲條款。喺條款變更後繼續使用 Lulgo 即表示你接受新條款。
            </p>
          </section>

          {/* Section 8 */}
          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">8. Contact / 聯絡我們</h2>
            <p className="mb-2">
              Questions? Contact us at:{' '}
              <a href="mailto:brian777asd@gmail.com" className="text-orange hover:underline">brian777asd@gmail.com</a>
            </p>
            <p className="text-gray-500">
              有問題？請聯絡：{' '}
              <a href="mailto:brian777asd@gmail.com" className="text-orange hover:underline">brian777asd@gmail.com</a>
            </p>
          </section>

        </div>
      </main>
    </div>
  )
}
