import type { Trip } from './types'

const LB = 'Long Beach'
const SD = 'San Diego'

function mapsUrl(name: string, city: string) {
  return `https://www.google.com/maps/search/${encodeURIComponent(`${name} ${city}`)}`
}
function reviewsUrl(name: string, city: string) {
  return `https://www.google.com/search?q=${encodeURIComponent(`${name} ${city} reviews`)}`
}
function yelpUrl(name: string, city: string) {
  return `https://www.yelp.com/search?find_desc=${encodeURIComponent(name)}&find_loc=${encodeURIComponent(city)}`
}

export const EXAMPLE_LONG_BEACH: Trip = {
  id: 'example-longbeach',
  title: 'Long Beach Day Trip',
  destination: LB,
  language: 'en',
  createdAt: '2026-03-01T10:00:00.000Z',
  days: [
    {
      dayNumber: 1,
      title: 'Waterfront, Bites & Belmont Shore',
      places: [
        {
          name: 'Aquarium of the Pacific',
          nameLocal: '太平洋水族館',
          type: 'attraction',
          arrivalTime: '9:00 AM',
          duration: '2–3 hours',
          description:
            'One of the largest aquariums in the US, home to over 11,000 animals including sea otters, sharks, and a free-flight bird aviary. The Tropical Pacific Gallery is a crowd favourite — arrive early on weekends to beat school groups.',
          address: '100 Aquarium Way, Long Beach, CA 90802',
          googleRating: 4.6,
          googleReviewCount: 33200,
          yelpRating: 4.0,
          yelpReviewCount: 2840,
          parking: {
            available: true,
            type: 'paid',
            details: 'Aquarium Way parking structure directly adjacent, $12–18/day.',
            tips: 'Arrive before 9 AM to snag a spot on the lower levels.',
          },
          tips: 'Buy tickets online in advance — saves $3 and skips the box-office queue.',
          googleMapsUrl: mapsUrl('Aquarium of the Pacific', LB),
          googleReviewsUrl: reviewsUrl('Aquarium of the Pacific', LB),
          yelpUrl: yelpUrl('Aquarium of the Pacific', LB),
          backupOptions: [
            {
              name: 'Queen Mary',
              description: 'Historic ocean liner turned hotel and attraction with fascinating ship tours and panoramic harbour views.',
              googleRating: 4.2,
              yelpRating: 3.5,
              address: '1126 Queens Hwy, Long Beach, CA 90802',
              googleMapsUrl: mapsUrl('Queen Mary', LB),
              yelpUrl: yelpUrl('Queen Mary', LB),
            },
            {
              name: 'El Dorado Nature Center',
              description: 'Peaceful 105-acre nature sanctuary with walking trails, a lake, and native bird watching — free to enter.',
              googleRating: 4.6,
              yelpRating: 4.5,
              address: '7550 E Spring St, Long Beach, CA 90815',
              googleMapsUrl: mapsUrl('El Dorado Nature Center', LB),
              yelpUrl: yelpUrl('El Dorado Nature Center', LB),
            },
          ],
        },
        {
          name: "Roscoe's House of Chicken & Waffles",
          nameLocal: '炸雞窩夫餐廳',
          type: 'restaurant',
          arrivalTime: '12:00 PM',
          duration: '1 hour',
          description:
            'An LA institution since 1975. Order the #1 — one succulent chicken breast with a golden waffle — or go big with the Country Boy (three wings + two waffles). The syrup-and-hot-sauce combo is non-negotiable.',
          address: '730 E Broadway, Long Beach, CA 90802',
          googleRating: 4.3,
          googleReviewCount: 2150,
          yelpRating: 4.0,
          yelpReviewCount: 1480,
          priceRange: '$$',
          parking: {
            available: true,
            type: 'street',
            details: 'Street parking on Broadway and side streets, usually free on Sundays.',
            tips: 'Try the small lot behind the building on weekdays.',
          },
          tips: 'Expect a short wait on weekends — the line moves fast and is worth it.',
          googleMapsUrl: mapsUrl("Roscoe's House of Chicken & Waffles", LB),
          googleReviewsUrl: reviewsUrl("Roscoe's House of Chicken & Waffles", LB),
          yelpUrl: yelpUrl("Roscoe's House of Chicken & Waffles", LB),
          backupOptions: [
            {
              name: `Lola's Mexican Cuisine`,
              description: 'Beloved neighbourhood spot with award-winning tamales, killer margaritas, and a festive patio.',
              googleRating: 4.4,
              yelpRating: 4.0,
              address: '2030 E 4th St, Long Beach, CA 90814',
              googleMapsUrl: mapsUrl("Lola's Mexican Cuisine", LB),
              yelpUrl: yelpUrl("Lola's Mexican Cuisine", LB),
            },
            {
              name: `George's Greek Café`,
              description: 'Casual Greek diner packed with locals, famous for giant gyros, spanakopita, and cheap lunch combos.',
              googleRating: 4.4,
              yelpRating: 4.0,
              address: '135 Pine Ave, Long Beach, CA 90802',
              googleMapsUrl: mapsUrl("George's Greek Café", LB),
              yelpUrl: yelpUrl("George's Greek Café", LB),
            },
          ],
        },
        {
          name: 'Shoreline Village',
          nameLocal: '海岸村',
          type: 'attraction',
          arrivalTime: '2:00 PM',
          duration: '1.5 hours',
          description:
            'A charming waterfront promenade lined with shops, ice cream stands, and restaurants overlooking Rainbow Harbour and the Queen Mary. Rent a surrey bike or just stroll and people-watch with the boats gliding by.',
          address: '401 Shoreline Village Dr, Long Beach, CA 90802',
          googleRating: 4.3,
          googleReviewCount: 5400,
          yelpRating: 3.5,
          yelpReviewCount: 760,
          parking: {
            available: true,
            type: 'paid',
            details: 'Shoreline Village surface lot, $3/hour. Validated with $10 purchase at most shops.',
          },
          tips: 'Walk to the end of the dock for the best unobstructed view of the Queen Mary.',
          googleMapsUrl: mapsUrl('Shoreline Village', LB),
          googleReviewsUrl: reviewsUrl('Shoreline Village', LB),
          yelpUrl: yelpUrl('Shoreline Village', LB),
          backupOptions: [
            {
              name: 'Bluff Park',
              description: 'Scenic clifftop park above the ocean with benches, rose gardens, and sweeping Pacific views.',
              googleRating: 4.6,
              yelpRating: 4.5,
              address: 'Ocean Blvd & Redondo Ave, Long Beach, CA 90803',
              googleMapsUrl: mapsUrl('Bluff Park Long Beach', LB),
              yelpUrl: yelpUrl('Bluff Park Long Beach', LB),
            },
            {
              name: 'Long Beach Museum of Art',
              description: 'Intimate museum set in a historic clifftop villa overlooking the ocean, with rotating contemporary exhibitions.',
              googleRating: 4.5,
              yelpRating: 4.0,
              address: '2300 E Ocean Blvd, Long Beach, CA 90803',
              googleMapsUrl: mapsUrl('Long Beach Museum of Art', LB),
              yelpUrl: yelpUrl('Long Beach Museum of Art', LB),
            },
          ],
        },
        {
          name: 'Belmont Shore — 2nd Street',
          nameLocal: '貝爾蒙特海岸',
          type: 'attraction',
          arrivalTime: '4:00 PM',
          duration: '1.5 hours',
          description:
            'Long Beach\'s liveliest neighbourhood strip, stretching six blocks with indie boutiques, wine bars, and dozens of restaurants. Perfect for a late-afternoon wander before dinner — the bookshops and local brands make great browsing.',
          address: '2nd St & Bayshore Ave, Long Beach, CA 90803',
          googleRating: 4.5,
          googleReviewCount: 1200,
          yelpRating: 4.0,
          yelpReviewCount: 340,
          parking: {
            available: true,
            type: 'street',
            details: 'Metered street parking on 2nd St, $1.25/hour. Free after 6 PM on most blocks.',
            tips: 'Try the residential side streets one block off 2nd for free spots.',
          },
          googleMapsUrl: mapsUrl('Belmont Shore 2nd Street', LB),
          googleReviewsUrl: reviewsUrl('Belmont Shore Long Beach', LB),
          yelpUrl: yelpUrl('Belmont Shore', LB),
          backupOptions: [
            {
              name: 'Retro Row (4th Street)',
              description: 'Quirky antique shops, vintage clothing stores, and independent cafés along a mile-long stretch of eclectic 4th Street.',
              googleRating: 4.5,
              yelpRating: 4.0,
              address: '4th St & Cherry Ave, Long Beach, CA 90802',
              googleMapsUrl: mapsUrl('Retro Row Long Beach', LB),
              yelpUrl: yelpUrl('Retro Row Long Beach', LB),
            },
            {
              name: 'Naples Island Canals',
              description: 'Walk the waterfront paths around Long Beach\'s Venice-inspired canal island — best in the early evening light.',
              googleRating: 4.7,
              yelpRating: 4.5,
              address: 'Naples Plaza, Long Beach, CA 90803',
              googleMapsUrl: mapsUrl('Naples Island Canals Long Beach', LB),
              yelpUrl: yelpUrl('Naples Island Long Beach', LB),
            },
          ],
        },
        {
          name: 'The Attic on Broadway',
          nameLocal: '閣樓餐廳',
          type: 'restaurant',
          arrivalTime: '6:30 PM',
          duration: '1.5 hours',
          description:
            'Long Beach\'s most talked-about comfort-food restaurant, set in a converted Craftsman bungalow. The mac & cheese is legendary — get it as a side with the truffle fries and short rib. Romantic porch seating fills up fast on weekends.',
          address: '3441 E Broadway, Long Beach, CA 90803',
          googleRating: 4.4,
          googleReviewCount: 1850,
          yelpRating: 4.0,
          yelpReviewCount: 940,
          priceRange: '$$$',
          parking: {
            available: true,
            type: 'street',
            details: 'Free street parking on E Broadway and surrounding residential streets.',
            tips: 'Metered spots on Broadway are free after 6 PM.',
          },
          tips: 'Make a reservation on OpenTable — walk-ins on Friday/Saturday can wait 45+ minutes.',
          googleMapsUrl: mapsUrl('The Attic on Broadway', LB),
          googleReviewsUrl: reviewsUrl('The Attic on Broadway', LB),
          yelpUrl: yelpUrl('The Attic on Broadway Long Beach', LB),
          backupOptions: [
            {
              name: 'Parkers Lighthouse',
              description: 'Upscale seafood restaurant with stunning waterfront views of the harbour and Queen Mary. Known for fresh Alaskan halibut and lobster bisque.',
              googleRating: 4.3,
              yelpRating: 3.5,
              address: '435 Shoreline Village Dr, Long Beach, CA 90802',
              googleMapsUrl: mapsUrl('Parkers Lighthouse', LB),
              yelpUrl: yelpUrl('Parkers Lighthouse Long Beach', LB),
            },
            {
              name: 'Spaghettini',
              description: 'Elegant Italian-American restaurant with live jazz on weekends, house-made pasta, and an extensive California wine list.',
              googleRating: 4.4,
              yelpRating: 4.0,
              address: '3005 Old Ranch Pkwy, Seal Beach, CA 90740',
              googleMapsUrl: mapsUrl('Spaghettini Seal Beach', 'Seal Beach'),
              yelpUrl: yelpUrl('Spaghettini', 'Seal Beach CA'),
            },
          ],
        },
        {
          name: 'Beachwood Brewing & Blendery',
          nameLocal: '海灘木釀酒廠',
          type: 'other',
          arrivalTime: '8:30 PM',
          duration: '1.5 hours',
          description:
            'Award-winning craft brewery with a taproom that\'s been voted one of the best in California. The sour barrel-aged blends are exceptional — try the Amalgamation or any seasonal IPA. Lively but not rowdy; great spot to end the day.',
          address: '210 E 3rd St, Long Beach, CA 90802',
          googleRating: 4.5,
          googleReviewCount: 1260,
          yelpRating: 4.5,
          yelpReviewCount: 830,
          parking: {
            available: true,
            type: 'street',
            details: 'Street parking on E 3rd St and Pine Ave, free after 8 PM.',
          },
          tips: 'Ask the bartender for a tasting flight before committing to a pint — the sours in particular vary widely.',
          googleMapsUrl: mapsUrl('Beachwood Brewing Blendery', LB),
          googleReviewsUrl: reviewsUrl('Beachwood Brewing Long Beach', LB),
          yelpUrl: yelpUrl('Beachwood Brewing Blendery', LB),
          backupOptions: [
            {
              name: 'The Pike Bar & Fish House',
              description: 'Lively waterfront bar with cold craft beers, fish tacos, and one of the best Happy Hours in downtown Long Beach.',
              googleRating: 4.2,
              yelpRating: 3.5,
              address: '95 Pine Ave, Long Beach, CA 90802',
              googleMapsUrl: mapsUrl('The Pike Bar Fish House', LB),
              yelpUrl: yelpUrl('The Pike Bar Fish House Long Beach', LB),
            },
            {
              name: 'Scoops Long Beach',
              description: 'Small-batch ice cream shop with inventive rotating flavours like lavender honey and brown butter pecan. Perfect nightcap for couples.',
              googleRating: 4.6,
              yelpRating: 4.5,
              address: '3415 E Broadway, Long Beach, CA 90803',
              googleMapsUrl: mapsUrl('Scoops Long Beach', LB),
              yelpUrl: yelpUrl('Scoops Long Beach', LB),
            },
          ],
        },
      ],
    },
  ],
}

export const EXAMPLE_SAN_DIEGO: Trip = {
  id: 'example-sandiego',
  title: 'San Diego 5-Day Getaway',
  destination: SD,
  language: 'en',
  createdAt: '2026-03-01T10:00:00.000Z',
  days: [
    {
      dayNumber: 1,
      title: 'Old Town & Gaslamp Quarter',
      places: [
        {
          name: 'Old Town San Diego State Historic Park',
          nameLocal: '聖地亞哥老城歷史公園',
          type: 'attraction',
          arrivalTime: '9:00 AM',
          duration: '2 hours',
          description:
            'The birthplace of California, with adobe buildings, live demos, and free museums set around a historic plaza. The Whaley House and Seeley Stables are worth your time — free admission to the park itself.',
          address: '4002 Wallace St, San Diego, CA 92110',
          googleRating: 4.6,
          googleReviewCount: 18400,
          yelpRating: 4.0,
          yelpReviewCount: 1940,
          parking: {
            available: true,
            type: 'free',
            details: 'Large free parking lot at Taylor St & San Diego Ave, just one block from the park.',
          },
          tips: 'Visit on a weekday morning for a quieter experience — weekends get crowded by 11 AM.',
          googleMapsUrl: mapsUrl('Old Town San Diego State Historic Park', SD),
          googleReviewsUrl: reviewsUrl('Old Town San Diego State Historic Park', SD),
          yelpUrl: yelpUrl('Old Town San Diego State Historic Park', SD),
          backupOptions: [
            {
              name: 'Mission Hills Neighborhood',
              description: 'Walkable residential neighbourhood with beautiful early-20th-century architecture, independent coffee shops, and antique stores.',
              googleRating: 4.5,
              yelpRating: 4.0,
              address: 'Fort Stockton Dr, San Diego, CA 92103',
              googleMapsUrl: mapsUrl('Mission Hills San Diego', SD),
              yelpUrl: yelpUrl('Mission Hills San Diego', SD),
            },
            {
              name: 'Presidio Park',
              description: 'Serene hilltop park with sweeping views over Mission Valley, the Junípero Serra Museum, and shaded walking paths.',
              googleRating: 4.6,
              yelpRating: 4.0,
              address: '2811 Jackson St, San Diego, CA 92110',
              googleMapsUrl: mapsUrl('Presidio Park San Diego', SD),
              yelpUrl: yelpUrl('Presidio Park San Diego', SD),
            },
          ],
        },
        {
          name: "El Agave Tequilería",
          nameLocal: '龍舌蘭墨西哥餐廳',
          type: 'restaurant',
          arrivalTime: '12:00 PM',
          duration: '1 hour',
          description:
            'Widely regarded as San Diego\'s finest Mexican restaurant — not a taco shop, but a proper sit-down tequilería with over 2,000 tequilas and mezcals. The mole negro and carnitas de pato (duck carnitas) are extraordinary.',
          address: '2304 San Diego Ave, San Diego, CA 92110',
          googleRating: 4.5,
          googleReviewCount: 2600,
          yelpRating: 4.0,
          yelpReviewCount: 1300,
          priceRange: '$$$',
          parking: {
            available: true,
            type: 'street',
            details: 'Street parking on San Diego Ave, free on Sundays.',
          },
          tips: 'Ask for the tequila flight — the knowledgeable staff will pair it with your meal.',
          googleMapsUrl: mapsUrl("El Agave Tequilería", SD),
          googleReviewsUrl: reviewsUrl("El Agave San Diego", SD),
          yelpUrl: yelpUrl("El Agave Tequileria", SD),
          backupOptions: [
            {
              name: "Café Coyote",
              description: 'Colourful Old Town classic with strolling mariachi, fresh-made tortillas at a station by the door, and reliable enchiladas.',
              googleRating: 4.3,
              yelpRating: 3.5,
              address: '2461 San Diego Ave, San Diego, CA 92110',
              googleMapsUrl: mapsUrl("Café Coyote Old Town San Diego", SD),
              yelpUrl: yelpUrl("Cafe Coyote San Diego", SD),
            },
            {
              name: "Casa Guadalajara",
              description: 'Beautifully decorated hacienda-style restaurant with a sprawling garden patio, strong margaritas, and generous combination plates.',
              googleRating: 4.4,
              yelpRating: 4.0,
              address: '4105 Taylor St, San Diego, CA 92110',
              googleMapsUrl: mapsUrl("Casa Guadalajara San Diego", SD),
              yelpUrl: yelpUrl("Casa Guadalajara San Diego", SD),
            },
          ],
        },
        {
          name: 'Balboa Park — Botanical Building',
          nameLocal: '巴波亞公園植物館',
          type: 'attraction',
          arrivalTime: '2:00 PM',
          duration: '2 hours',
          description:
            'Even if you skip the museums (there are 17), the park itself is spectacular. The lath Botanical Building with its lily pond reflection is one of the most photogenic spots in San Diego. The central El Prado promenade lined with Spanish colonial facades is stunning at golden hour.',
          address: '1549 El Prado, San Diego, CA 92101',
          googleRating: 4.8,
          googleReviewCount: 42000,
          yelpRating: 4.5,
          yelpReviewCount: 3200,
          parking: {
            available: true,
            type: 'free',
            details: 'Free parking throughout the park — Pan American Rd lot is closest to the Botanical Building.',
            tips: 'Weekends fill up by noon. Try the Inspiration Point parking lot off Presidents Way for overflow.',
          },
          tips: 'Tuesday is free admission day at most Balboa Park museums — check the schedule at balboapark.org.',
          googleMapsUrl: mapsUrl('Balboa Park Botanical Building', SD),
          googleReviewsUrl: reviewsUrl('Balboa Park San Diego', SD),
          yelpUrl: yelpUrl('Balboa Park', SD),
          backupOptions: [
            {
              name: 'San Diego Museum of Art',
              description: 'The largest art museum in San Diego, housed in a gorgeous Spanish Plateresque building with works spanning 5,000 years.',
              googleRating: 4.6,
              yelpRating: 4.0,
              address: '1450 El Prado, San Diego, CA 92101',
              googleMapsUrl: mapsUrl('San Diego Museum of Art', SD),
              yelpUrl: yelpUrl('San Diego Museum of Art', SD),
            },
            {
              name: 'San Diego Zoo',
              description: 'World-famous zoo home to 3,700 animals and a must-see giant panda habitat. Buy tickets online to avoid the queue.',
              googleRating: 4.7,
              yelpRating: 4.5,
              address: '2920 Zoo Dr, San Diego, CA 92101',
              googleMapsUrl: mapsUrl('San Diego Zoo', SD),
              yelpUrl: yelpUrl('San Diego Zoo', SD),
            },
          ],
        },
        {
          name: "Hodad's Downtown",
          nameLocal: '霍達德漢堡',
          type: 'restaurant',
          arrivalTime: '6:00 PM',
          duration: '1 hour',
          description:
            'San Diego\'s most iconic burger joint — licence plates on the walls, massive double-patty burgers with shredded lettuce and hand-cut fries. Order the bacon cheeseburger and a milkshake. Cash-friendly and no-nonsense.',
          address: '945 Broadway, San Diego, CA 92101',
          googleRating: 4.5,
          googleReviewCount: 5800,
          yelpRating: 4.0,
          yelpReviewCount: 2900,
          priceRange: '$$',
          parking: {
            available: true,
            type: 'paid',
            details: 'Street meters and nearby parking structures on Broadway, $2–3/hour.',
          },
          tips: 'The line moves faster than it looks. If the wait is over 30 minutes, the Ocean Beach location is equally good.',
          googleMapsUrl: mapsUrl("Hodad's Downtown", SD),
          googleReviewsUrl: reviewsUrl("Hodad's San Diego", SD),
          yelpUrl: yelpUrl("Hodad's", SD),
          backupOptions: [
            {
              name: "Phil's BBQ",
              description: 'San Diego BBQ legend with fall-off-the-bone St. Louis ribs, monster portions, and a sauce worth bottling.',
              googleRating: 4.6,
              yelpRating: 4.0,
              address: '3750 Sports Arena Blvd, San Diego, CA 92110',
              googleMapsUrl: mapsUrl("Phil's BBQ San Diego", SD),
              yelpUrl: yelpUrl("Phil's BBQ", SD),
            },
            {
              name: 'Puesto at the Headquarters',
              description: 'Modern Mexican restaurant in the historic Headquarters building with creative tacos like crispy avocado and filet mignon.',
              googleRating: 4.5,
              yelpRating: 4.0,
              address: '789 W Harbor Dr, San Diego, CA 92101',
              googleMapsUrl: mapsUrl('Puesto at the Headquarters San Diego', SD),
              yelpUrl: yelpUrl('Puesto San Diego Headquarters', SD),
            },
          ],
        },
        {
          name: 'Gaslamp Quarter Evening Stroll',
          nameLocal: '煤氣燈區夜遊',
          type: 'other',
          arrivalTime: '8:00 PM',
          duration: '1.5 hours',
          description:
            'San Diego\'s 16-block Victorian-era entertainment district lights up at night with rooftop bars, live music venues, and street performers. Grab a craft cocktail at Prohibition or enjoy live jazz at Croce\'s Park West — the energy on weekend nights is electric.',
          address: 'Fifth Ave & J St, San Diego, CA 92101',
          googleRating: 4.3,
          googleReviewCount: 12800,
          yelpRating: 3.5,
          yelpReviewCount: 2100,
          parking: {
            available: true,
            type: 'paid',
            details: 'Multiple parking structures along 6th Ave, $10–15 flat rate after 6 PM.',
          },
          tips: 'Avoid driving back — rideshare is cheap from the Gaslamp and parking structures fill quickly after 9 PM.',
          googleMapsUrl: mapsUrl('Gaslamp Quarter', SD),
          googleReviewsUrl: reviewsUrl('Gaslamp Quarter San Diego', SD),
          yelpUrl: yelpUrl('Gaslamp Quarter', SD),
          backupOptions: [
            {
              name: 'Little Italy Food Hall',
              description: 'Vibrant food hall with a dozen vendors, outdoor seating, and a lively bar scene on India St.',
              googleRating: 4.4,
              yelpRating: 4.0,
              address: '550 W Date St, San Diego, CA 92101',
              googleMapsUrl: mapsUrl('Little Italy Food Hall San Diego', SD),
              yelpUrl: yelpUrl('Little Italy Food Hall San Diego', SD),
            },
            {
              name: 'Stone Brewing World Bistro & Gardens — Liberty Station',
              description: 'Massive craft beer campus in a repurposed naval training center with 40+ taps and excellent wood-fired food.',
              googleRating: 4.5,
              yelpRating: 4.0,
              address: '2816 Historic Decatur Rd, San Diego, CA 92106',
              googleMapsUrl: mapsUrl('Stone Brewing Liberty Station San Diego', SD),
              yelpUrl: yelpUrl('Stone Brewing Liberty Station', SD),
            },
          ],
        },
      ],
    },
    {
      dayNumber: 2,
      title: 'SeaWorld & Mission Beach',
      places: [
        {
          name: 'SeaWorld San Diego',
          nameLocal: '聖地亞哥海洋世界',
          type: 'attraction',
          arrivalTime: '9:00 AM',
          duration: '5–6 hours',
          description:
            'Go early for the dolphins and orcas at Explorer\'s Reef, then hit Electric Eel (the 4G coaster) before the lunch crowds arrive. The penguin encounter in the Wild Arctic zone is a hidden gem most visitors skip.',
          address: '500 SeaWorld Dr, San Diego, CA 92109',
          googleRating: 4.4,
          googleReviewCount: 48000,
          yelpRating: 3.5,
          yelpReviewCount: 5200,
          parking: {
            available: true,
            type: 'paid',
            details: 'On-site parking $25/day; Preferred Parking $35 (closer to entrance).',
            tips: 'Buy parking in advance online to save $5 and skip the toll plaza queue.',
          },
          tips: 'Book the Dolphin Interaction experience ($65/person) weeks ahead — it sells out fast and is genuinely unforgettable.',
          googleMapsUrl: mapsUrl('SeaWorld San Diego', SD),
          googleReviewsUrl: reviewsUrl('SeaWorld San Diego', SD),
          yelpUrl: yelpUrl('SeaWorld San Diego', SD),
          backupOptions: [
            {
              name: 'San Diego Zoo Safari Park',
              description: 'Open-air safari experience in Escondido with rhinos, elephants, and giraffes you can get surprisingly close to.',
              googleRating: 4.7,
              yelpRating: 4.5,
              address: '15500 San Pasqual Valley Rd, Escondido, CA 92027',
              googleMapsUrl: mapsUrl('San Diego Zoo Safari Park', 'Escondido CA'),
              yelpUrl: yelpUrl('San Diego Zoo Safari Park', 'Escondido CA'),
            },
            {
              name: 'USS Midway Museum',
              description: 'America\'s longest-serving 20th-century aircraft carrier turned world-class naval aviation museum, docked at the Embarcadero.',
              googleRating: 4.8,
              yelpRating: 4.5,
              address: '910 N Harbor Dr, San Diego, CA 92101',
              googleMapsUrl: mapsUrl('USS Midway Museum San Diego', SD),
              yelpUrl: yelpUrl('USS Midway Museum', SD),
            },
          ],
        },
        {
          name: "World Famous",
          type: 'restaurant',
          arrivalTime: '3:30 PM',
          duration: '1 hour',
          description:
            'A Mission Beach institution with a full ocean view, open since 1959. The fish tacos and clam chowder are the draw — order at the counter, grab a window seat, and watch the waves while you eat. It gets loud but the vibe is pure San Diego.',
          address: '711 Pacific Beach Dr, San Diego, CA 92109',
          googleRating: 4.2,
          googleReviewCount: 3100,
          yelpRating: 3.5,
          yelpReviewCount: 2800,
          priceRange: '$$',
          parking: {
            available: true,
            type: 'street',
            details: 'Metered street parking on Mission Blvd and Pacific Beach Dr, $2/hour.',
            tips: 'Lots fill up fast in summer — arrive by 3 PM or use the structure on Garnet Ave.',
          },
          googleMapsUrl: mapsUrl('World Famous Restaurant Pacific Beach San Diego', SD),
          googleReviewsUrl: reviewsUrl('World Famous Restaurant San Diego', SD),
          yelpUrl: yelpUrl('World Famous San Diego', SD),
          backupOptions: [
            {
              name: "Kono's Cafe",
              description: 'No-frills beachfront breakfast spot famous for the Kono\'s burrito — scrambled eggs, cheese, potatoes in a flour tortilla griddled crispy.',
              googleRating: 4.5,
              yelpRating: 4.0,
              address: '704 Garnet Ave, Pacific Beach, CA 92109',
              googleMapsUrl: mapsUrl("Kono's Cafe Pacific Beach", SD),
              yelpUrl: yelpUrl("Kono's Cafe San Diego", SD),
            },
            {
              name: 'Slater\'s 50/50',
              description: 'Craft burger bar known for its signature 50/50 patty (half beef, half bacon) and an obscene list of beer options.',
              googleRating: 4.4,
              yelpRating: 4.0,
              address: '2750 Dewey Rd, San Diego, CA 92106',
              googleMapsUrl: mapsUrl("Slater's 50/50 San Diego", SD),
              yelpUrl: yelpUrl("Slater's 50/50 San Diego", SD),
            },
          ],
        },
        {
          name: 'Mission Beach Boardwalk',
          nameLocal: '使命海灘木板路',
          type: 'attraction',
          arrivalTime: '5:00 PM',
          duration: '1.5 hours',
          description:
            'A 3-mile oceanfront path perfect for a sunset walk, bike ride, or roller skate. Belmont Park\'s historic Giant Dipper wooden roller coaster sits at the south end — $7 a ride and completely worth it for the nostalgia.',
          address: 'Mission Blvd & W Mission Bay Dr, San Diego, CA 92109',
          googleRating: 4.5,
          googleReviewCount: 9800,
          yelpRating: 4.0,
          yelpReviewCount: 1400,
          parking: {
            available: true,
            type: 'paid',
            details: 'Belmont Park parking lot, $5–12 depending on time of day.',
          },
          tips: 'Bike rentals at Mission Beach Club ($10/hour) are a great way to cover more of the boardwalk.',
          googleMapsUrl: mapsUrl('Mission Beach Boardwalk San Diego', SD),
          googleReviewsUrl: reviewsUrl('Mission Beach Boardwalk San Diego', SD),
          yelpUrl: yelpUrl('Mission Beach Boardwalk San Diego', SD),
          backupOptions: [
            {
              name: 'Ocean Beach Pier',
              description: 'One of the longest wooden piers on the West Coast — free to walk, great for fishing and sunset watching.',
              googleRating: 4.6,
              yelpRating: 4.0,
              address: 'Niagara Ave & Abbott St, San Diego, CA 92107',
              googleMapsUrl: mapsUrl('Ocean Beach Pier San Diego', SD),
              yelpUrl: yelpUrl('Ocean Beach Pier San Diego', SD),
            },
            {
              name: 'Fiesta Island',
              description: 'Quiet park loop around a bay island, popular with dog owners and kayakers, great for a peaceful sunset drive or jog.',
              googleRating: 4.6,
              yelpRating: 4.5,
              address: 'Fiesta Island Rd, San Diego, CA 92109',
              googleMapsUrl: mapsUrl('Fiesta Island San Diego', SD),
              yelpUrl: yelpUrl('Fiesta Island San Diego', SD),
            },
          ],
        },
        {
          name: "Phil's BBQ — Sports Arena",
          nameLocal: '菲爾燒烤',
          type: 'restaurant',
          arrivalTime: '7:00 PM',
          duration: '1 hour',
          description:
            'San Diego\'s BBQ royalty — the St. Louis-style pork ribs are slow-smoked to perfection, falling off the bone with their house smoke rub. The portions are enormous; the half-rack with two sides is plenty for one person. Cash only at this location.',
          address: '3750 Sports Arena Blvd, San Diego, CA 92110',
          googleRating: 4.6,
          googleReviewCount: 6400,
          yelpRating: 4.0,
          yelpReviewCount: 3800,
          priceRange: '$$',
          parking: {
            available: true,
            type: 'free',
            details: 'Large free parking lot shared with the Sports Arena complex.',
          },
          tips: 'Arrive by 7 PM or expect a 30–45 minute wait. Phil\'s doesn\'t take reservations.',
          googleMapsUrl: mapsUrl("Phil's BBQ Sports Arena San Diego", SD),
          googleReviewsUrl: reviewsUrl("Phil's BBQ San Diego", SD),
          yelpUrl: yelpUrl("Phil's BBQ San Diego Sports Arena", SD),
          backupOptions: [
            {
              name: 'Brigantine Seafood & Oyster Bar',
              description: 'San Diego seafood institution since 1969 — fresh fish, oysters on the half shell, and a legendary Friday Fish Fry.',
              googleRating: 4.4,
              yelpRating: 4.0,
              address: '2444 San Diego Ave, San Diego, CA 92110',
              googleMapsUrl: mapsUrl('Brigantine Seafood San Diego', SD),
              yelpUrl: yelpUrl('Brigantine Seafood San Diego', SD),
            },
            {
              name: 'Crack Shack',
              description: 'Richard Blais\'s wildly popular fried chicken restaurant with craft cocktails, a bocce court, and the best chicken sandwich in the city.',
              googleRating: 4.5,
              yelpRating: 4.0,
              address: '2266 Kettner Blvd, San Diego, CA 92101',
              googleMapsUrl: mapsUrl('Crack Shack San Diego', SD),
              yelpUrl: yelpUrl('Crack Shack San Diego', SD),
            },
          ],
        },
        {
          name: 'Pacific Beach Bar & Grill',
          type: 'other',
          arrivalTime: '9:00 PM',
          duration: '1.5 hours',
          description:
            'Sprawling two-story beachfront bar with an open-air upper deck, fire pits, and live music most nights. The vibe is relaxed San Diego beach culture at its best — cold craft beers, ocean breeze, and a crowd that\'s actually having fun.',
          address: '860 Garnet Ave, Pacific Beach, CA 92109',
          googleRating: 4.0,
          googleReviewCount: 2200,
          yelpRating: 3.5,
          yelpReviewCount: 1600,
          parking: {
            available: true,
            type: 'street',
            details: 'Metered parking on Garnet Ave, free after 8 PM.',
          },
          googleMapsUrl: mapsUrl('Pacific Beach Bar Grill San Diego', SD),
          googleReviewsUrl: reviewsUrl('Pacific Beach Bar Grill San Diego', SD),
          yelpUrl: yelpUrl('Pacific Beach Bar Grill', SD),
          backupOptions: [
            {
              name: 'Duck Dive',
              description: 'Beloved neighbourhood bar in Pacific Beach with an excellent beer list, pool tables, and a no-attitude crowd.',
              googleRating: 4.5,
              yelpRating: 4.0,
              address: '4650 Mission Blvd, San Diego, CA 92109',
              googleMapsUrl: mapsUrl('Duck Dive Bar Pacific Beach', SD),
              yelpUrl: yelpUrl('Duck Dive San Diego', SD),
            },
            {
              name: 'Prohibition',
              description: '1920s speakeasy-style cocktail bar in the Gaslamp with craft cocktails and intimate booth seating.',
              googleRating: 4.4,
              yelpRating: 4.0,
              address: '548 5th Ave, San Diego, CA 92101',
              googleMapsUrl: mapsUrl('Prohibition Bar San Diego', SD),
              yelpUrl: yelpUrl('Prohibition Lounge San Diego', SD),
            },
          ],
        },
      ],
    },
    {
      dayNumber: 3,
      title: 'La Jolla Cove & Coastal Walk',
      places: [
        {
          name: 'La Jolla Cove',
          nameLocal: '拉霍亞灣',
          type: 'attraction',
          arrivalTime: '9:00 AM',
          duration: '2 hours',
          description:
            'One of Southern California\'s most beautiful spots — a small sheltered cove surrounded by cliffs, packed with sea lions and leopard sharks in the shallows. Snorkel the ecological reserve or just watch from the bluffs above. The early morning light here is stunning.',
          address: '1100 Coast Blvd, La Jolla, CA 92037',
          googleRating: 4.8,
          googleReviewCount: 38000,
          yelpRating: 4.5,
          yelpReviewCount: 3400,
          parking: {
            available: true,
            type: 'paid',
            details: 'Metered parking on Coast Blvd, $2/hour. Lots on Prospect St, $10/day.',
            tips: 'Arrive before 9 AM on summer weekends — the cove and surrounding streets fill completely by 10 AM.',
          },
          tips: 'Walk south along the Coast Walk Trail for stunning cliff views that most tourists miss entirely.',
          googleMapsUrl: mapsUrl('La Jolla Cove', 'La Jolla CA'),
          googleReviewsUrl: reviewsUrl('La Jolla Cove', 'La Jolla CA'),
          yelpUrl: yelpUrl('La Jolla Cove', 'La Jolla CA'),
          backupOptions: [
            {
              name: 'Torrey Pines State Natural Reserve',
              description: 'Dramatic coastal cliffs and one of the rarest pine trees in North America. The Beach Trail to the ocean is extraordinary.',
              googleRating: 4.8,
              yelpRating: 4.5,
              address: '12600 N Torrey Pines Rd, La Jolla, CA 92037',
              googleMapsUrl: mapsUrl('Torrey Pines State Natural Reserve', 'La Jolla CA'),
              yelpUrl: yelpUrl('Torrey Pines State Natural Reserve', 'La Jolla CA'),
            },
            {
              name: 'Windansea Beach',
              description: 'Rugged, reef-heavy beach popular with surfers and those who want a less crowded La Jolla experience.',
              googleRating: 4.7,
              yelpRating: 4.5,
              address: '6800 Neptune Pl, La Jolla, CA 92037',
              googleMapsUrl: mapsUrl('Windansea Beach La Jolla', 'La Jolla CA'),
              yelpUrl: yelpUrl('Windansea Beach La Jolla', 'La Jolla CA'),
            },
          ],
        },
        {
          name: 'The Cottage La Jolla',
          nameLocal: '拉霍亞小屋餐廳',
          type: 'restaurant',
          arrivalTime: '11:30 AM',
          duration: '1 hour',
          description:
            'Beloved La Jolla brunch institution in a converted 1920s cottage with a garden patio. The lemon ricotta pancakes and avocado eggs benedict are the signature dishes. Consistently rated one of the best breakfasts in San Diego.',
          address: '7702 Fay Ave, La Jolla, CA 92037',
          googleRating: 4.5,
          googleReviewCount: 3800,
          yelpRating: 4.0,
          yelpReviewCount: 2200,
          priceRange: '$$$',
          parking: {
            available: true,
            type: 'street',
            details: 'Metered street parking on Fay Ave and surrounding streets.',
          },
          tips: 'Waits of 30–45 minutes are normal on weekends. Put your name in and explore the village while you wait.',
          googleMapsUrl: mapsUrl('The Cottage La Jolla', 'La Jolla CA'),
          googleReviewsUrl: reviewsUrl('The Cottage La Jolla', 'La Jolla CA'),
          yelpUrl: yelpUrl('The Cottage La Jolla', 'La Jolla CA'),
          backupOptions: [
            {
              name: "George's at the Cove",
              description: 'La Jolla landmark with jaw-dropping ocean views from the rooftop terrace. The California Modern menu is exceptional.',
              googleRating: 4.6,
              yelpRating: 4.0,
              address: '1250 Prospect St, La Jolla, CA 92037',
              googleMapsUrl: mapsUrl("George's at the Cove La Jolla", 'La Jolla CA'),
              yelpUrl: yelpUrl("George's at the Cove", 'La Jolla CA'),
            },
            {
              name: 'Brockton Villa',
              description: 'Historic beach cottage restaurant overlooking the cove, famous for Coast Toast (a french toast soufflé) and fresh omelets.',
              googleRating: 4.4,
              yelpRating: 4.0,
              address: '1235 Coast Blvd, La Jolla, CA 92037',
              googleMapsUrl: mapsUrl('Brockton Villa La Jolla', 'La Jolla CA'),
              yelpUrl: yelpUrl('Brockton Villa La Jolla', 'La Jolla CA'),
            },
          ],
        },
        {
          name: 'La Jolla Village Galleries & Prospect Street',
          nameLocal: '拉霍亞藝廊街',
          type: 'attraction',
          arrivalTime: '1:00 PM',
          duration: '2 hours',
          description:
            'La Jolla\'s upscale shopping and gallery district, with fine art galleries, jewellers, and boutique clothing stores along Prospect and Girard. The Museum of Contemporary Art San Diego (MCASD) is here — free for San Diego residents.',
          address: '700 Prospect St, La Jolla, CA 92037',
          googleRating: 4.6,
          googleReviewCount: 4200,
          yelpRating: 4.0,
          yelpReviewCount: 780,
          parking: {
            available: true,
            type: 'paid',
            details: 'Parking structure on Herschel Ave, $2/hour. Some street meters.',
          },
          googleMapsUrl: mapsUrl('Prospect Street La Jolla', 'La Jolla CA'),
          googleReviewsUrl: reviewsUrl('La Jolla Village', 'La Jolla CA'),
          yelpUrl: yelpUrl('La Jolla Village', 'La Jolla CA'),
          backupOptions: [
            {
              name: 'Museum of Contemporary Art San Diego',
              description: 'Landmark museum perched above the cove with permanent and rotating contemporary collections and incredible views.',
              googleRating: 4.5,
              yelpRating: 4.0,
              address: '700 Prospect St, La Jolla, CA 92037',
              googleMapsUrl: mapsUrl('Museum of Contemporary Art San Diego La Jolla', 'La Jolla CA'),
              yelpUrl: yelpUrl('Museum of Contemporary Art San Diego', 'La Jolla CA'),
            },
            {
              name: 'Birch Aquarium at Scripps',
              description: 'Outstanding aquarium at Scripps Institution of Oceanography with massive kelp forest tank and sea horse nursery.',
              googleRating: 4.6,
              yelpRating: 4.0,
              address: '2300 Expedition Way, La Jolla, CA 92037',
              googleMapsUrl: mapsUrl('Birch Aquarium Scripps La Jolla', 'La Jolla CA'),
              yelpUrl: yelpUrl('Birch Aquarium at Scripps', 'La Jolla CA'),
            },
          ],
        },
        {
          name: 'Puesto La Jolla',
          nameLocal: '拉霍亞墨西哥餐廳',
          type: 'restaurant',
          arrivalTime: '6:30 PM',
          duration: '1.5 hours',
          description:
            'The best of San Diego\'s modern taco scene — the crispy chicken and filet mignon tacos on house-made corn tortillas are genuinely spectacular. The margaritas are made with freshly squeezed juice. Lively, beautiful room with an outdoor terrace.',
          address: '1026 Wall St, La Jolla, CA 92037',
          googleRating: 4.6,
          googleReviewCount: 4100,
          yelpRating: 4.0,
          yelpReviewCount: 1800,
          priceRange: '$$$',
          parking: {
            available: true,
            type: 'paid',
            details: 'Parking structure on Herschel Ave, $2–3/hour.',
          },
          tips: 'Make a reservation — this spot gets slammed on weekend evenings by 7 PM.',
          googleMapsUrl: mapsUrl('Puesto La Jolla', 'La Jolla CA'),
          googleReviewsUrl: reviewsUrl('Puesto La Jolla', 'La Jolla CA'),
          yelpUrl: yelpUrl('Puesto La Jolla', 'La Jolla CA'),
          backupOptions: [
            {
              name: 'Duke\'s La Jolla',
              description: 'Hawaiian-themed ocean view restaurant with excellent fresh fish, mai tais, and a fantastic sunset happy hour.',
              googleRating: 4.4,
              yelpRating: 3.5,
              address: '1216 Prospect St, La Jolla, CA 92037',
              googleMapsUrl: mapsUrl("Duke's La Jolla", 'La Jolla CA'),
              yelpUrl: yelpUrl("Duke's La Jolla", 'La Jolla CA'),
            },
            {
              name: 'Whisknladle',
              description: 'Farm-to-table La Jolla institution with an ingredient-driven menu that changes with the seasons and a celebrated craft cocktail program.',
              googleRating: 4.5,
              yelpRating: 4.0,
              address: '1044 Wall St, La Jolla, CA 92037',
              googleMapsUrl: mapsUrl('Whisknladle La Jolla', 'La Jolla CA'),
              yelpUrl: yelpUrl('Whisknladle La Jolla', 'La Jolla CA'),
            },
          ],
        },
        {
          name: 'La Jolla Cove Sunset Walk',
          type: 'other',
          arrivalTime: '8:30 PM',
          duration: '1 hour',
          description:
            'After dinner, walk back to the cove for the evening sea lion show — dozens lounge on the rocks as the sun drops below the horizon. The cliffside path south toward Children\'s Pool is magical at dusk with the lights of the village behind you.',
          address: '1100 Coast Blvd, La Jolla, CA 92037',
          googleRating: 4.8,
          googleReviewCount: 38000,
          yelpRating: 4.5,
          yelpReviewCount: 3400,
          parking: {
            available: true,
            type: 'paid',
            details: 'Coast Blvd street meters free after 8 PM.',
          },
          googleMapsUrl: mapsUrl('La Jolla Cove sunset', 'La Jolla CA'),
          googleReviewsUrl: reviewsUrl('La Jolla Cove', 'La Jolla CA'),
          yelpUrl: yelpUrl('La Jolla Cove', 'La Jolla CA'),
          backupOptions: [
            {
              name: 'Children\'s Pool Beach',
              description: 'Small crescent beach famous for its resident harbour seal colony — they haul out along the sea wall year-round.',
              googleRating: 4.5,
              yelpRating: 4.0,
              address: '850 Coast Blvd, La Jolla, CA 92037',
              googleMapsUrl: mapsUrl("Children's Pool Beach La Jolla", 'La Jolla CA'),
              yelpUrl: yelpUrl("Children's Pool Beach La Jolla", 'La Jolla CA'),
            },
            {
              name: 'Rooftop at George\'s',
              description: 'Rooftop bar above George\'s at the Cove — the best nightcap in La Jolla with 180° ocean views and strong cocktails.',
              googleRating: 4.6,
              yelpRating: 4.0,
              address: '1250 Prospect St, La Jolla, CA 92037',
              googleMapsUrl: mapsUrl("George's at the Cove Rooftop La Jolla", 'La Jolla CA'),
              yelpUrl: yelpUrl("George's at the Cove Rooftop", 'La Jolla CA'),
            },
          ],
        },
      ],
    },
    {
      dayNumber: 4,
      title: 'Little Italy & Embarcadero',
      places: [
        {
          name: 'Little Italy Farmers Market',
          nameLocal: '小意大利農夫市場',
          type: 'attraction',
          arrivalTime: '9:00 AM',
          duration: '1.5 hours',
          description:
            'One of San Diego\'s best farmers markets, running every Saturday along Date and India Streets. Local produce, artisan food stalls, fresh flowers, and street food from a rotating cast of vendors — the breakfast burritos and crepes are a morning institution.',
          address: '550 W Date St, San Diego, CA 92101',
          googleRating: 4.7,
          googleReviewCount: 3600,
          yelpRating: 4.5,
          yelpReviewCount: 1200,
          parking: {
            available: true,
            type: 'paid',
            details: 'Little Italy parking structure on Elm St, $5 flat on Saturdays.',
          },
          tips: 'Runs Saturdays 8 AM–2 PM. The Mona Lisa Italian deli stall sells incredible porchetta sandwiches — get there before 11 AM.',
          googleMapsUrl: mapsUrl('Little Italy Farmers Market San Diego', SD),
          googleReviewsUrl: reviewsUrl('Little Italy Farmers Market San Diego', SD),
          yelpUrl: yelpUrl('Little Italy Farmers Market San Diego', SD),
          backupOptions: [
            {
              name: 'Hillcrest Farmers Market',
              description: 'San Diego\'s oldest and most diverse farmers market, Sunday mornings, with excellent food stalls and a strong local community vibe.',
              googleRating: 4.6,
              yelpRating: 4.5,
              address: 'Normal St & Lincoln Ave, San Diego, CA 92103',
              googleMapsUrl: mapsUrl('Hillcrest Farmers Market San Diego', SD),
              yelpUrl: yelpUrl('Hillcrest Farmers Market San Diego', SD),
            },
            {
              name: 'North Park Farmers Market',
              description: 'Thursday evening market in the hipster heart of San Diego with craft food, live music, and local vendors.',
              googleRating: 4.5,
              yelpRating: 4.0,
              address: '3100 Ray St, San Diego, CA 92104',
              googleMapsUrl: mapsUrl('North Park Farmers Market San Diego', SD),
              yelpUrl: yelpUrl('North Park Farmers Market San Diego', SD),
            },
          ],
        },
        {
          name: "Café Calabria",
          type: 'restaurant',
          arrivalTime: '11:00 AM',
          duration: '45 min',
          description:
            'A serious espresso bar in North Park that roasts its own beans in-house. The single-origin pour-overs are exceptional, and the ricotta toast with honey is a perfect light bite. Beloved by San Diego\'s specialty coffee crowd.',
          address: '3933 30th St, San Diego, CA 92104',
          googleRating: 4.5,
          googleReviewCount: 1800,
          yelpRating: 4.0,
          yelpReviewCount: 820,
          priceRange: '$',
          parking: {
            available: true,
            type: 'street',
            details: 'Free street parking on 30th St.',
          },
          googleMapsUrl: mapsUrl("Café Calabria North Park San Diego", SD),
          googleReviewsUrl: reviewsUrl("Cafe Calabria San Diego", SD),
          yelpUrl: yelpUrl("Cafe Calabria San Diego", SD),
          backupOptions: [
            {
              name: 'Better Buzz Coffee',
              description: 'San Diego homegrown coffee chain known for lavender lattes and thick Nutella toast. Multiple locations, always packed.',
              googleRating: 4.5,
              yelpRating: 4.0,
              address: '4302 Mission Blvd, San Diego, CA 92109',
              googleMapsUrl: mapsUrl('Better Buzz Coffee San Diego', SD),
              yelpUrl: yelpUrl('Better Buzz Coffee San Diego', SD),
            },
            {
              name: 'Dark Horse Coffee Roasters',
              description: 'Industrial-chic South Park roastery known for the strongest espresso in the city and a no-nonsense coffee philosophy.',
              googleRating: 4.5,
              yelpRating: 4.0,
              address: '2668 Historic Decatur Rd, San Diego, CA 92106',
              googleMapsUrl: mapsUrl('Dark Horse Coffee Roasters San Diego', SD),
              yelpUrl: yelpUrl('Dark Horse Coffee Roasters San Diego', SD),
            },
          ],
        },
        {
          name: 'USS Midway Museum',
          nameLocal: '中途島號航空母艦博物館',
          type: 'attraction',
          arrivalTime: '1:00 PM',
          duration: '3 hours',
          description:
            'The most visited naval vessel museum in the world — climb through a 1,001-ft aircraft carrier with 30 restored aircraft on deck. The self-guided audio tour (voiced by former crew) is excellent. Kids and adults are equally obsessed with the flight simulators.',
          address: '910 N Harbor Dr, San Diego, CA 92101',
          googleRating: 4.8,
          googleReviewCount: 52000,
          yelpRating: 4.5,
          yelpReviewCount: 6200,
          parking: {
            available: true,
            type: 'paid',
            details: 'Navy Pier parking lot adjacent to museum, $15–20/day.',
            tips: 'The Embarcadero lot on Harbor Dr is often cheaper and just a 3-minute walk.',
          },
          tips: 'Buy tickets online for $5 off. Go on a weekday if you can — weekends get genuinely crowded on the flight deck.',
          googleMapsUrl: mapsUrl('USS Midway Museum San Diego', SD),
          googleReviewsUrl: reviewsUrl('USS Midway Museum San Diego', SD),
          yelpUrl: yelpUrl('USS Midway Museum San Diego', SD),
          backupOptions: [
            {
              name: 'Maritime Museum of San Diego',
              description: 'Fleet of historic ships including the Star of India (the world\'s oldest active sailing ship, 1863) and a Soviet submarine.',
              googleRating: 4.6,
              yelpRating: 4.0,
              address: '1492 N Harbor Dr, San Diego, CA 92101',
              googleMapsUrl: mapsUrl('Maritime Museum San Diego', SD),
              yelpUrl: yelpUrl('Maritime Museum San Diego', SD),
            },
            {
              name: 'New Children\'s Museum',
              description: 'Architecture-forward interactive arts museum in downtown San Diego, designed for hands-on exploration by kids of all ages.',
              googleRating: 4.5,
              yelpRating: 4.0,
              address: '200 W Island Ave, San Diego, CA 92101',
              googleMapsUrl: mapsUrl("New Children's Museum San Diego", SD),
              yelpUrl: yelpUrl("New Children's Museum San Diego", SD),
            },
          ],
        },
        {
          name: 'Ironside Fish & Oyster',
          nameLocal: '鐵側魚類牡蠣餐廳',
          type: 'restaurant',
          arrivalTime: '6:30 PM',
          duration: '1.5 hours',
          description:
            'Little Italy\'s celebrated seafood bar with the best oyster selection in San Diego and an exceptional raw bar. The chowder fries (clam chowder poured over crinkle-cut fries) are a signature indulgence. Gorgeous nautical interior, great cocktails.',
          address: '1654 India St, San Diego, CA 92101',
          googleRating: 4.5,
          googleReviewCount: 4800,
          yelpRating: 4.0,
          yelpReviewCount: 2600,
          priceRange: '$$$',
          parking: {
            available: true,
            type: 'paid',
            details: 'Little Italy parking structure on Elm St, $5–8 evenings.',
          },
          tips: 'Happy hour weekdays 3–6 PM has $1.50 oysters and discounted cocktails — plan accordingly.',
          googleMapsUrl: mapsUrl('Ironside Fish Oyster Little Italy San Diego', SD),
          googleReviewsUrl: reviewsUrl('Ironside Fish Oyster San Diego', SD),
          yelpUrl: yelpUrl('Ironside Fish Oyster San Diego', SD),
          backupOptions: [
            {
              name: 'Juniper & Ivy',
              description: 'Richard Blais\'s flagship San Diego restaurant in a converted 1920s warehouse with a stunning open kitchen and inventive California cuisine.',
              googleRating: 4.5,
              yelpRating: 4.0,
              address: '2228 Kettner Blvd, San Diego, CA 92101',
              googleMapsUrl: mapsUrl('Juniper and Ivy San Diego', SD),
              yelpUrl: yelpUrl('Juniper and Ivy San Diego', SD),
            },
            {
              name: 'Carnitas\' Snack Shack',
              description: 'Beloved pork-focused gastropub in Little Italy with the Triple Threat Pork Sandwich (pork belly + pulled pork + pork schnitzel) as the star.',
              googleRating: 4.4,
              yelpRating: 4.0,
              address: '1004 N Harbor Dr, San Diego, CA 92101',
              googleMapsUrl: mapsUrl("Carnitas' Snack Shack San Diego", SD),
              yelpUrl: yelpUrl("Carnitas Snack Shack San Diego", SD),
            },
          ],
        },
        {
          name: 'Little Italy Rooftop Bar Crawl',
          type: 'other',
          arrivalTime: '9:00 PM',
          duration: '1.5 hours',
          description:
            'Little Italy has quietly become the best rooftop bar neighbourhood in San Diego. Start at raised by wolves (inside University Heights, but worth the trip) or stay local at the rooftop at Kettner Exchange — panoramic views over the bay, strong craft cocktails, and a scene that actually feels cool rather than tryhard.',
          address: 'India St & Date St, San Diego, CA 92101',
          googleRating: 4.4,
          googleReviewCount: 1800,
          yelpRating: 4.0,
          yelpReviewCount: 640,
          parking: {
            available: true,
            type: 'paid',
            details: 'Use the Little Italy parking structure — no point moving the car for a bar crawl.',
          },
          tips: 'Uber or Lyft between neighbourhoods — parking is brutal and rideshare is cheap in San Diego.',
          googleMapsUrl: mapsUrl('Little Italy San Diego nightlife', SD),
          googleReviewsUrl: reviewsUrl('Little Italy San Diego bars', SD),
          yelpUrl: yelpUrl('Little Italy bars nightlife', SD),
          backupOptions: [
            {
              name: 'Raised by Wolves',
              description: 'Hidden gem cocktail bar accessed through a fake bookcase in a University Heights market — theatrical, meticulously crafted drinks.',
              googleRating: 4.6,
              yelpRating: 4.5,
              address: '3001 El Cajon Blvd, San Diego, CA 92104',
              googleMapsUrl: mapsUrl('Raised by Wolves San Diego', SD),
              yelpUrl: yelpUrl('Raised by Wolves San Diego', SD),
            },
            {
              name: 'Coin-Op Game Room',
              description: 'Craft cocktail bar with 50+ vintage arcade games — great if you want a lively but different kind of evening.',
              googleRating: 4.5,
              yelpRating: 4.0,
              address: '3926 30th St, San Diego, CA 92104',
              googleMapsUrl: mapsUrl('Coin-Op Game Room San Diego', SD),
              yelpUrl: yelpUrl('Coin-Op Game Room San Diego', SD),
            },
          ],
        },
      ],
    },
    {
      dayNumber: 5,
      title: 'Coronado Island & Farewell Brunch',
      places: [
        {
          name: 'Hotel del Coronado Beach',
          nameLocal: '科羅納多酒店海灘',
          type: 'attraction',
          arrivalTime: '9:00 AM',
          duration: '2 hours',
          description:
            'The white sand beach in front of the iconic Hotel del Coronado — one of the most photographed buildings in California. Even if you\'re not staying, the beach is public and the Victorian red-roofed hotel is a spectacular backdrop. The walk along the shore at low tide is magnificent.',
          address: '1500 Orange Ave, Coronado, CA 92118',
          googleRating: 4.8,
          googleReviewCount: 28000,
          yelpRating: 4.5,
          yelpReviewCount: 4200,
          parking: {
            available: true,
            type: 'paid',
            details: 'Hotel del Coronado parking $10–25/day. Free street parking 2 blocks away on Glorietta Blvd.',
            tips: 'Cross on the Coronado Ferry ($5.25 each way) from the Embarcadero for a scenic approach — no parking headaches.',
          },
          tips: 'The ferry is the best way to arrive — the view of downtown San Diego from the water is superb.',
          googleMapsUrl: mapsUrl('Hotel del Coronado Beach', 'Coronado CA'),
          googleReviewsUrl: reviewsUrl('Hotel del Coronado Coronado', 'Coronado CA'),
          yelpUrl: yelpUrl('Hotel del Coronado Beach', 'Coronado CA'),
          backupOptions: [
            {
              name: 'Coronado Central Beach',
              description: 'Four miles of wide, uncrowded white sand beach with views of the San Diego skyline and Point Loma — the best urban beach in Southern California.',
              googleRating: 4.8,
              yelpRating: 4.5,
              address: 'Ocean Blvd, Coronado, CA 92118',
              googleMapsUrl: mapsUrl('Coronado Central Beach', 'Coronado CA'),
              yelpUrl: yelpUrl('Coronado Beach', 'Coronado CA'),
            },
            {
              name: 'Silver Strand State Beach',
              description: 'Quieter beach south of Coronado connecting to the Silver Strand, with calm bay waters on one side and ocean surf on the other.',
              googleRating: 4.6,
              yelpRating: 4.0,
              address: '5000 CA-75, Coronado, CA 92118',
              googleMapsUrl: mapsUrl('Silver Strand State Beach Coronado', 'Coronado CA'),
              yelpUrl: yelpUrl('Silver Strand State Beach', 'Coronado CA'),
            },
          ],
        },
        {
          name: 'Miguel\'s Cocina — Coronado',
          nameLocal: '科羅納多墨西哥餐廳',
          type: 'restaurant',
          arrivalTime: '11:30 AM',
          duration: '1 hour',
          description:
            'Lively Mexican restaurant right on Orange Ave with some of the best carne asada burritos in the region and legendary frozen margaritas. The mahi mahi fish tacos and shrimp enchiladas are the move at lunch. Great patio seating.',
          address: '1351 Orange Ave, Coronado, CA 92118',
          googleRating: 4.4,
          googleReviewCount: 2800,
          yelpRating: 4.0,
          yelpReviewCount: 1600,
          priceRange: '$$',
          parking: {
            available: true,
            type: 'street',
            details: 'Street parking on Orange Ave, metered, $1.50/hour.',
          },
          googleMapsUrl: mapsUrl("Miguel's Cocina Coronado", 'Coronado CA'),
          googleReviewsUrl: reviewsUrl("Miguel's Cocina Coronado", 'Coronado CA'),
          yelpUrl: yelpUrl("Miguel's Cocina Coronado", 'Coronado CA'),
          backupOptions: [
            {
              name: 'Brigantine Seafood Coronado',
              description: 'Coronado outpost of the beloved SD seafood chain with excellent Fish Fridays and a reliable happy hour.',
              googleRating: 4.4,
              yelpRating: 4.0,
              address: '1333 Orange Ave, Coronado, CA 92118',
              googleMapsUrl: mapsUrl('Brigantine Coronado', 'Coronado CA'),
              yelpUrl: yelpUrl('Brigantine Seafood Coronado', 'Coronado CA'),
            },
            {
              name: 'Nado Gelato',
              description: 'Artisan Italian gelato shop on Orange Ave — end the morning with a scoop of salted caramel or pistachio before heading back.',
              googleRating: 4.7,
              yelpRating: 4.5,
              address: '1031 Orange Ave, Coronado, CA 92118',
              googleMapsUrl: mapsUrl('Nado Gelato Coronado', 'Coronado CA'),
              yelpUrl: yelpUrl('Nado Gelato Coronado', 'Coronado CA'),
            },
          ],
        },
        {
          name: 'Orange Avenue, Coronado',
          nameLocal: '科羅納多橙大道',
          type: 'attraction',
          arrivalTime: '1:00 PM',
          duration: '1.5 hours',
          description:
            'Coronado\'s charming main street with independent boutiques, surf shops, ice cream parlours, and the gorgeous historic Coronado Ferry Landing. A relaxed afternoon stroll before heading back to San Diego.',
          address: 'Orange Ave, Coronado, CA 92118',
          googleRating: 4.6,
          googleReviewCount: 3200,
          yelpRating: 4.0,
          yelpReviewCount: 820,
          parking: {
            available: true,
            type: 'street',
            details: 'Metered parking throughout the Orange Ave district.',
          },
          googleMapsUrl: mapsUrl('Orange Avenue Coronado', 'Coronado CA'),
          googleReviewsUrl: reviewsUrl('Orange Avenue Coronado', 'Coronado CA'),
          yelpUrl: yelpUrl('Orange Avenue Coronado', 'Coronado CA'),
          backupOptions: [
            {
              name: 'Coronado Ferry Landing Marketplace',
              description: 'Waterfront shopping promenade with the best unobstructed view of the San Diego downtown skyline across the bay.',
              googleRating: 4.5,
              yelpRating: 4.0,
              address: '1201 1st St, Coronado, CA 92118',
              googleMapsUrl: mapsUrl('Coronado Ferry Landing', 'Coronado CA'),
              yelpUrl: yelpUrl('Coronado Ferry Landing Marketplace', 'Coronado CA'),
            },
            {
              name: 'Coronado Historical Association Museum',
              description: 'Free museum chronicling Coronado Island\'s fascinating history from its founding to its role in WWII naval aviation.',
              googleRating: 4.5,
              yelpRating: 4.0,
              address: '1100 Orange Ave, Coronado, CA 92118',
              googleMapsUrl: mapsUrl('Coronado Historical Association Museum', 'Coronado CA'),
              yelpUrl: yelpUrl('Coronado Historical Association Museum', 'Coronado CA'),
            },
          ],
        },
        {
          name: 'Coasterra',
          nameLocal: '海岸墨西哥餐廳',
          type: 'restaurant',
          arrivalTime: '7:00 PM',
          duration: '2 hours',
          description:
            'The most spectacular farewell dinner location in San Diego — a waterfront restaurant on Harbor Island with floor-to-ceiling glass and an unobstructed view of the Coronado Bridge and downtown skyline at night. Upscale coastal Mexican cuisine: the whole roasted sea bass and wood-fired lobster are the headliners.',
          address: '880 Harbor Island Dr, San Diego, CA 92101',
          googleRating: 4.5,
          googleReviewCount: 3800,
          yelpRating: 4.0,
          yelpReviewCount: 2200,
          priceRange: '$$$$',
          parking: {
            available: true,
            type: 'free',
            details: 'Free valet and self-parking in the Harbor Island lot.',
          },
          tips: 'Request a window table when booking — the view of the Coronado Bridge is the point.',
          googleMapsUrl: mapsUrl('Coasterra San Diego', SD),
          googleReviewsUrl: reviewsUrl('Coasterra San Diego', SD),
          yelpUrl: yelpUrl('Coasterra San Diego Harbor Island', SD),
          backupOptions: [
            {
              name: 'Mitch\'s Seafood',
              description: 'Local favourite fish market and casual restaurant in Point Loma with the freshest catch in the city, eaten at picnic tables.',
              googleRating: 4.6,
              yelpRating: 4.0,
              address: '1403 Scott St, San Diego, CA 92106',
              googleMapsUrl: mapsUrl("Mitch's Seafood San Diego", SD),
              yelpUrl: yelpUrl("Mitch's Seafood San Diego", SD),
            },
            {
              name: 'Island Prime & C Level Lounge',
              description: 'Waterfront steakhouse on Harbor Island with the same stunning skyline view — ideal if the group wants steak over seafood.',
              googleRating: 4.5,
              yelpRating: 4.0,
              address: '880 Harbor Island Dr, San Diego, CA 92101',
              googleMapsUrl: mapsUrl('Island Prime San Diego', SD),
              yelpUrl: yelpUrl('Island Prime San Diego', SD),
            },
          ],
        },
        {
          name: 'Coronado Bridge Night View',
          nameLocal: '科羅納多大橋夜景',
          type: 'other',
          arrivalTime: '9:30 PM',
          duration: '45 min',
          description:
            'Drive or walk to the Embarcadero Waterfront Park after dinner for the best night view of the illuminated Coronado Bridge arching over the bay. The combination of the bridge lights, Coronado\'s silhouette, and the downtown skyline is a genuinely breathtaking last memory of San Diego.',
          address: 'Embarcadero Marina Park North, San Diego, CA 92101',
          googleRating: 4.7,
          googleReviewCount: 8400,
          yelpRating: 4.5,
          yelpReviewCount: 1100,
          parking: {
            available: true,
            type: 'free',
            details: 'Free parking along North Harbor Dr after 10 PM.',
          },
          googleMapsUrl: mapsUrl('Embarcadero Marina Park San Diego', SD),
          googleReviewsUrl: reviewsUrl('Coronado Bridge view San Diego', SD),
          yelpUrl: yelpUrl('Embarcadero Marina Park North San Diego', SD),
          backupOptions: [
            {
              name: 'Sunset Cliffs Natural Park',
              description: 'Dramatic coastal cliffs in Ocean Beach — the most spectacular sunset-watching spot in San Diego, hands down.',
              googleRating: 4.8,
              yelpRating: 4.5,
              address: '1590 Sunset Cliffs Blvd, San Diego, CA 92107',
              googleMapsUrl: mapsUrl('Sunset Cliffs Natural Park San Diego', SD),
              yelpUrl: yelpUrl('Sunset Cliffs Natural Park San Diego', SD),
            },
            {
              name: 'Cabrillo National Monument',
              description: 'Historic lighthouse and bluff with the most expansive panoramic view of San Diego Bay and the Pacific — stunning at any hour.',
              googleRating: 4.8,
              yelpRating: 4.5,
              address: '1800 Cabrillo Memorial Dr, San Diego, CA 92106',
              googleMapsUrl: mapsUrl('Cabrillo National Monument San Diego', SD),
              yelpUrl: yelpUrl('Cabrillo National Monument San Diego', SD),
            },
          ],
        },
      ],
    },
  ],
}

export const EXAMPLE_TRIPS: Record<string, Trip> = {
  'example-longbeach': EXAMPLE_LONG_BEACH,
  'example-sandiego': EXAMPLE_SAN_DIEGO,
}
