import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import { getTrip } from '@/lib/storage'
import { DayCard } from '@/components/DayCard'
import { ShareButton } from '@/components/ShareButton'

export const revalidate = false // cache forever

type Props = { params: Promise<{ id: string }> }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params
  const trip = await getTrip(id)
  if (!trip) return { title: 'Trip not found' }

  return {
    title: trip.title,
    description: `${trip.days.length}-day trip to ${trip.destination} — generated by TripGenie`,
    openGraph: {
      title: trip.title,
      description: `${trip.days.length}-day trip to ${trip.destination}`,
      images: trip.ogImageUrl
        ? [{ url: trip.ogImageUrl, width: 1200, height: 630 }]
        : [{ url: '/og-fallback.png', width: 1200, height: 630 }],
    },
  }
}

export default async function TripPage({ params }: Props) {
  const { id } = await params
  const trip = await getTrip(id)
  if (!trip) notFound()

  const tripUrl = `/trip/${id}`

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header
        className="text-white px-4 pt-8 pb-6"
        style={{ background: 'linear-gradient(180deg, #1a3a5c 0%, #2d5a8e 100%)' }}
      >
        <div className="max-w-xl mx-auto">
          <p className="text-xs text-orange font-semibold mb-1">✨ TripGenie</p>
          <h1 className="text-2xl font-bold leading-tight mb-1">{trip.title}</h1>
          <p className="text-sm opacity-70 mb-4">
            {trip.destination} · {trip.days.length} day{trip.days.length !== 1 ? 's' : ''}
          </p>

          {/* Share bar */}
          <div className="bg-white/10 backdrop-blur-sm rounded-xl p-3 flex items-center justify-between gap-3">
            <span className="text-xs opacity-75 truncate font-mono">
              tripgenie.app{tripUrl}
            </span>
            <ShareButton tripId={id} />
          </div>
        </div>
      </header>

      {/* Day tabs + content */}
      <main className="max-w-xl mx-auto px-4 py-4">
        {/* Disclaimer */}
        <div className="text-xs text-amber-700 bg-amber-50 border border-amber-100 rounded-lg px-3 py-2 mb-4">
          ⚠️ 評分為 AI 估算 / Ratings are AI-estimated. Verify on Yelp & Google before visiting.
        </div>

        {trip.days.map(day => (
          <DayCard key={day.dayNumber} day={day} />
        ))}

        {/* Footer */}
        <footer className="text-center text-xs text-gray-400 py-8">
          Made with ✨ <a href="/" className="text-orange underline">TripGenie</a>
        </footer>
      </main>
    </div>
  )
}
