import { notFound } from 'next/navigation'
import { headers } from 'next/headers'
import type { Metadata } from 'next'
import { getTrip } from '@/lib/storage'
import { EXAMPLE_TRIPS } from '@/lib/example-trips'
import { ShareButton } from '@/components/ShareButton'
import { ExportButton } from '@/components/ExportButton'
import { ExampleTripViewer } from '@/components/ExampleTripViewer'
import { TripEditor } from '@/components/TripEditor'
import { SaveRecentTrip } from '@/components/SaveRecentTrip'

export const dynamic = 'force-dynamic'
export const fetchCache = 'force-no-store'

type Props = { params: Promise<{ id: string }> }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params
  const trip = EXAMPLE_TRIPS[id] ?? await getTrip(id)
  if (!trip) return { title: 'Trip not found' }

  return {
    title: trip.title,
    description: `${Math.max(...trip.days.map(d => d.dayNumber))}-day trip to ${trip.destination} — generated by Lulgo`,
    openGraph: {
      title: trip.title,
      description: `${Math.max(...trip.days.map(d => d.dayNumber))}-day trip to ${trip.destination}`,
      images: trip.ogImageUrl
        ? [{ url: trip.ogImageUrl, width: 1200, height: 630 }]
        : [{ url: '/og-fallback.png', width: 1200, height: 630 }],
    },
  }
}

export default async function TripPage({ params }: Props) {
  // Force dynamic rendering — read headers to defeat any caching layer
  const headersList = await headers()
  void headersList

  const { id } = await params

  // Example trips: served from hardcoded data with a client-side skeleton
  if (EXAMPLE_TRIPS[id]) {
    return <ExampleTripViewer trip={EXAMPLE_TRIPS[id]} />
  }

  const trip = await getTrip(id)
  if (!trip) notFound()

  const tripUrl = `/trip/${id}`

  return (
    <div className="min-h-screen bg-gray-50">
      <SaveRecentTrip
        id={id}
        title={trip.title}
        destination={trip.destination}
        days={Math.max(...trip.days.map(d => d.dayNumber))}
        createdAt={trip.createdAt}
      />
      {/* Header */}
      <header className="relative z-10 text-white px-4 pt-8 pb-6">
        {/* Background: hero image or navy gradient (overflow-hidden only on bg to avoid clipping dropdown) */}
        <div className="absolute inset-0 overflow-hidden">
          {trip.heroImageUrl ? (
            <>
              <img
                src={trip.heroImageUrl}
                alt={trip.destination}
                className="absolute inset-0 w-full h-full object-cover"
              />
              {/* Dark overlay for text legibility */}
              <div className="absolute inset-0" style={{ background: 'linear-gradient(180deg, rgba(0,0,0,0.55) 0%, rgba(0,0,0,0.72) 100%)' }} />
            </>
          ) : (
            <div className="absolute inset-0" style={{ background: 'linear-gradient(180deg, var(--color-navy) 0%, var(--color-navy-mid) 100%)' }} />
          )}
        </div>

        {/* Content */}
        <div className="relative max-w-4xl mx-auto">
          <p className="text-xs text-orange font-semibold mb-1">Lulgo</p>
          <h1 className="text-2xl font-bold leading-tight mb-1">{trip.title}</h1>
          <p className="text-sm opacity-80 mb-4">
            {trip.destination} · {(() => {
              const cn = trip.language === 'zh-TW' || trip.language === 'zh-HK' || trip.language === 'zh-CN'
              const numDays = Math.max(...trip.days.map(d => d.dayNumber))
              return cn ? `${numDays}日` : `${numDays} day${numDays !== 1 ? 's' : ''}`
            })()}
          </p>

          {/* Share bar */}
          <div className="bg-white/10 backdrop-blur-sm rounded-xl p-3 flex items-center justify-between gap-3">
            <span className="text-xs opacity-90 truncate font-mono">
              lulgo.com{tripUrl}
            </span>
            <div className="flex items-center gap-2">
              <ExportButton trip={trip} />
              <ShareButton tripId={id} tripTitle={trip.title} language={trip.language} trip={trip} />
            </div>
          </div>

          {/* Photo credit (Unsplash attribution requirement) */}
          {trip.heroImageCredit && (
            <p className="mt-2 text-right text-xs opacity-50">
              Photo by{' '}
              <a
                href={trip.heroImageCredit.link}
                target="_blank"
                rel="noopener noreferrer"
                className="underline hover:opacity-75"
              >
                {trip.heroImageCredit.name}
              </a>
              {' '}on Unsplash
            </p>
          )}
        </div>
      </header>

      {/* Day content + edit bar */}
      <main className="relative z-0 max-w-4xl mx-auto px-4 py-4">
        <TripEditor tripId={id} trip={trip} />

        {/* Viral CTA — pre-fill destination */}
        <div className="mt-6 mb-4">
          <a
            href={`/?dest=${encodeURIComponent(trip.destination)}&days=${Math.max(...trip.days.map(d => d.dayNumber))}`}
            className="flex items-center justify-center w-full bg-orange text-white py-3 rounded-xl font-semibold text-sm hover:opacity-90 transition-opacity focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange focus-visible:ring-offset-2"
          >
            {trip.language === 'zh-TW' || trip.language === 'zh-HK' || trip.language === 'zh-CN'
              ? `✨ 規劃類似行程 → ${trip.destination}`
              : `✨ Plan a trip like this → ${trip.destination}`
            }
          </a>
        </div>

        {/* Footer */}
        <footer className="text-center text-xs text-gray-400 py-8 pb-24">
          Made with <a href="/" className="text-orange underline">Lulgo</a>
        </footer>
      </main>
    </div>
  )
}
