import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import { getTrip } from '@/lib/storage'
import { EXAMPLE_TRIPS } from '@/lib/example-trips'
import { TripItinerary } from '@/components/TripItinerary'
import { TripMap } from '@/components/TripMap'
import { ShareButton } from '@/components/ShareButton'
import { ExampleTripViewer } from '@/components/ExampleTripViewer'

export const revalidate = false // cache forever

type Props = { params: Promise<{ id: string }> }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params
  const trip = EXAMPLE_TRIPS[id] ?? await getTrip(id)
  if (!trip) return { title: 'Trip not found' }

  return {
    title: trip.title,
    description: `${Math.max(...trip.days.map(d => d.dayNumber))}-day trip to ${trip.destination} — generated by TripGenie`,
    openGraph: {
      title: trip.title,
      description: `${Math.max(...trip.days.map(d => d.dayNumber))}-day trip to ${trip.destination}`,
      images: trip.ogImageUrl
        ? [{ url: trip.ogImageUrl, width: 1200, height: 630 }]
        : [{ url: '/og-fallback.png', width: 1200, height: 630 }],
    },
  }
}

export default async function TripPage({ params }: Props) {
  const { id } = await params

  // Example trips: served from hardcoded data with a client-side skeleton
  if (EXAMPLE_TRIPS[id]) {
    return <ExampleTripViewer trip={EXAMPLE_TRIPS[id]} />
  }

  const trip = await getTrip(id)
  if (!trip) notFound()

  const tripUrl = `/trip/${id}`

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="relative text-white px-4 pt-8 pb-6 overflow-hidden">
        {/* Background: hero image or navy gradient */}
        {trip.heroImageUrl ? (
          <>
            <img
              src={trip.heroImageUrl}
              alt={trip.destination}
              className="absolute inset-0 w-full h-full object-cover"
            />
            {/* Dark overlay for text legibility */}
            <div className="absolute inset-0" style={{ background: 'linear-gradient(180deg, rgba(0,0,0,0.55) 0%, rgba(0,0,0,0.72) 100%)' }} />
          </>
        ) : (
          <div className="absolute inset-0" style={{ background: 'linear-gradient(180deg, var(--color-navy) 0%, var(--color-navy-mid) 100%)' }} />
        )}

        {/* Content */}
        <div className="relative max-w-4xl mx-auto">
          <p className="text-xs text-orange font-semibold mb-1">TripGenie</p>
          <h1 className="text-2xl font-bold leading-tight mb-1">{trip.title}</h1>
          <p className="text-sm opacity-80 mb-4">
            {trip.destination} · {Math.max(...trip.days.map(d => d.dayNumber))} day{Math.max(...trip.days.map(d => d.dayNumber)) !== 1 ? 's' : ''}
          </p>

          {/* Share bar */}
          <div className="bg-white/10 backdrop-blur-sm rounded-xl p-3 flex items-center justify-between gap-3">
            <span className="text-xs opacity-90 truncate font-mono">
              tripgenie.app{tripUrl}
            </span>
            <ShareButton tripId={id} tripTitle={trip.title} />
          </div>

          {/* Photo credit (Unsplash attribution requirement) */}
          {trip.heroImageCredit && (
            <p className="mt-2 text-right text-xs opacity-50">
              Photo by{' '}
              <a
                href={trip.heroImageCredit.link}
                target="_blank"
                rel="noopener noreferrer"
                className="underline hover:opacity-75"
              >
                {trip.heroImageCredit.name}
              </a>
              {' '}on Unsplash
            </p>
          )}
        </div>
      </header>

      {/* Day content */}
      <main className="max-w-4xl mx-auto px-4 py-4">
        <TripMap days={trip.days} />
        <TripItinerary initialDays={trip.days} validated={trip.validated === true} showYelp={trip.language === 'en'} />

        {/* Create new trip CTA */}
        <div className="mt-6 mb-4">
          <a
            href="/"
            className="flex items-center justify-center w-full bg-orange text-white py-3 rounded-xl font-semibold text-sm hover:opacity-90 transition-opacity focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange focus-visible:ring-offset-2"
          >
            建立新行程 / Create New Trip
          </a>
        </div>

        {/* Footer */}
        <footer className="text-center text-xs text-gray-400 py-8">
          Made with <a href="/" className="text-orange underline">TripGenie</a>
        </footer>
      </main>
    </div>
  )
}
